---
- name: ubuntu apt sources list
  template: src=etc/apt/sources.list dest=/etc/apt/sources.list
  when: cuttle.ubuntu_mirror

- name: force-update apt cache
  apt: update_cache=yes cache_valid_time=1
  when: cuttle.apt.force_cache_update|bool
  register: result
  until: result|succeeded
  retries: 5

- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600
  register: result
  until: result|succeeded
  retries: 5

- name: do apt upgrade
  apt: upgrade=yes
  when: cuttle.apt.do_upgrade
  register: result
  until: result|succeeded
  retries: 5

- name: root user pip config directory
  file: dest=/root/.pip state=directory
  when: cuttle.python.pypi_mirror

- name: pip config file
  template: src=python/pip.conf dest=/root/.pip/pip.conf
  when: cuttle.python.pypi_mirror

- name: easyinstall config file
  template: src=python/pydistutils.cfg dest=/root/.pydistutils.cfg
  when: cuttle.python.pypi_mirror

- name: set up gem sources if needed
  template: src=ruby/gemrc dest=/root/.gemrc
  when: cuttle.ruby.gem_sources

- name: nuke gem sources if unused
  file: dest=/root/.gemrc state=absent
  when: not cuttle.ruby.gem_sources

- name: nuke user_install gems for root
  file:
    path: /root/.gem
    state: absent

- name: clean out sensu checks
  shell: "rm -f /etc/sensu/conf.d/checks/*"
  failed_when: false
  when: delete_all_sensu_checks|default('False')|bool
