---
dependencies:
  - role: runtime/ruby
    tags: ruby
  - role: runtime/python
    tags: python
  - role: apt-repos
    repos:
      - repo: 'deb {{ apt_repos.hwraid.repo }} trusty main'
        key_url: '{{ apt_repos.hwraid.key_url }}'
    purge_repos:
      - repo: 'deb {{ apt_repos.hwraid.repo }} precise main'
      - repo: 'deb http://apt-mirror.openstack.blueboxgrid.com/sysdig/stable/deb/ stable-$(ARCH)/'
    when: common.hwraid.enabled|bool
  - role: serverspec
    tags: ['serverspec']
    when: serverspec.enabled|default("True")|bool
  - role: logging-config
    service: common
    logdata: "{{ common.logs }}"
    forward_type: "{{ common.logging.forwarder }}"
    when: logging.enabled|default("True")|bool
  - role: sensu-check
  - role: users
    tags: users
