---
# needed when not running playbooks/add-bastion-users.yml
- name: set users_to_add when not defined
  set_fact:
    users_to_add: "{{ users }}"
  when: users_to_add is not defined

- include: yubiauthd.yml
  when:
    - twofa.enabled|default("False")|bool
    - twofa.method == "yubiauthd"
  tags: yubiauthd

- include: google-2fa.yml
  when:
    - twofa.enabled|default("False")|bool
    - twofa.method == "google"
  tags: google-2fa


- include: utils.yml
  when: yama_utils.enabled|default("False")|bool
  tags: yama_utils

- include: checks.yml
  when: sensu.client.enable_checks|default('True')|bool
  tags: sensu-checks

- include: metrics.yml
  when: sensu.client.enable_metrics|default('True')|bool
  tags: sensu-metrics

- include: serverspec.yml
  when: serverspec.enabled|default("True")|bool
  tags: serverspec
