---
dependencies:
  - role: apache
  - role: bbg-ssl
    name: "{{ openid_proxy.apache.ssl.name }}"
    ssl_cert: "{{ openid_proxy.apache.ssl.cert }}"
    ssl_key: "{{ openid_proxy.apache.ssl.key }}"
    ssl_intermediate: "{{ openid_proxy.apache.ssl.intermediate }}"
    ssl_ca_cert: ~
    when: openid_proxy.apache.ssl.enabled
    tags: ['bbg-ssl']
  - role: logging-config
    service: openid_proxy
    logdata: "{{ openid_proxy.logs }}"
    forward_type: "{{ openid_proxy.logging.forwarder }}"
    when: logging.enabled|default("True")|bool
  - role: sensu-check
