---
- name: set grafana request url
  set_fact:
    grafana_url: http://127.0.0.1:{{ grafana.server.http_port }}/api/datasources

- name: check if grafana datasources exist
  uri:
    url: "{{ grafana_url }}"
    method: GET
    user: "{{ grafana.security.admin_user }}"
    password: "{{ grafana.security.admin_password }}"
    force_basic_auth: yes
    return_content: yes
  register: grafana_api_datasources

- name: create empty list for currently configured datasources
  set_fact:
    configured_datasources: []

- name: append to list of currently configured datasources
  set_fact:
    configured_datasources: "{{ configured_datasources + [item.name|lower] }}"
  with_items: "{{ grafana_api_datasources.content|default('{}')|from_json }}"

- name: add new grafana datasources
  uri:
    url: "{{ grafana_url }}"
    method: POST
    user: "{{ grafana.security.admin_user }}"
    password: "{{ grafana.security.admin_password }}"
    force_basic_auth: yes
    body: "{{ item | to_json }}"
    body_format: json
  with_items: "{{ grafana.datasources }}"
  when: item.name|lower not in configured_datasources
