---
- name: enable apache mods for file-mirror
  apache2_module: name={{ item }}
  with_items:
    - proxy_http
    - rewrite
    - headers

- name: add file_mirror apache vhost
  template: src=etc/apache2/sites-available/file_mirror
            dest=/etc/apache2/sites-available/file_mirror.conf
  notify:
    - restart apache

- name: enable file_mirror vhost
  apache2_site: state=enabled name=file_mirror
  notify:
    - restart apache

- meta: flush_handlers

- name: ensure apache is running
  service: name=apache2 state=started enabled=yes
