---
public_device_interface: eth1
private_device_interface: eth0
public_interface: ansible_eth1
private_interface: ansible_eth0
public_ipv4: "{{ hostvars[inventory_hostname][public_interface]['ipv4'] }}"
private_ipv4: "{{ hostvars[inventory_hostname][private_interface]['ipv4'] }}"

etc_hosts:
  - name: "{{ ttyspy.server.host }}"
    ip: "{{ ttyspy.server.ip }}"
  - name: bastion01
    ip: 172.16.0.150
  - name: bastion02
    ip: 172.16.0.151
  - name: ttyspy01
    ip: 172.16.0.152

common:
  ssh:
    github_authorized_keys:
      enabled: False
      api_url: ~ # ex: https://github.ghe.com/api/v3
      api_user: ~
      api_pass: ~

bastion:
  backdoor_user: vagrant
  ssh_port: 22
  force_commands:
    - /usr/bin/ttyspy
    - /usr/bin/ssh-mosh-filter
  users: ~

_users:
  manage_authorized_keys: true

twofa:
  enabled: "{{ twofa_enabled|default('false')|bool }}"
  method: google

user_groups:
  default:
    system: yes
  admin:
    system: yes
    ssh_keys:
      enable_passphrase: false
      fingerprint: "64:f3:60:f0:33:ed:8b:a3:af:33:c3:c1:e6:c8:41:bf"
      private: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEowIBAAKCAQEA34Tz/TDvjmcZkDiWmbm6Zz4jx1bl4rcEiSpbxYRqyXvxbGkG
        e+YoDyy5s+M/tKaP+kAYDbXwJM6NnLq8q4YsEeqszjDE3+qgH54TE8EoT1VoPDkl
        iUiE3a0d1DLZT8oX7x8y+q+39qQFN2sjTf39VgMpbWy6zOH7Ok9hpJXMItezuX9B
        sMOfHE3TgZdYnRlc9tRmI58+igw1E2reNqHBxWu2c4FdydoakTXgUmcLLheKW0xC
        m0NG9Cy5oAdq79ZJruuQQxTy9W71xm6W4EreDMCZrR3JWBvH2Ahv2JcDdj8BEB2g
        iYzwzSqM4D3l44jza2BULgoXf58JS/8B7LkryQIDAQABAoIBAE6ba1M3yofCKnNV
        82DMuIlmiR6pqN86jhXPF8c28nc5Z4ZAyU75ek0b5ZMl8FmP2kKgF9V6jqHjIlpk
        McYAwa7rYSqCbDpzQSzdYsgnvg1oc+f6EQFex5tOLpdZ6qLs583oov0WnxPWSx9a
        Rmg/UsDVC9S30FoNf1TaZfSD2e7GVOCohXSXheQnRs5AkovlieoBy8NbaRj9+ey3
        hTsbtAsMk7WiazHpP/Fl7LwAXSHRgtFl+s1dbSYbpBLWdabB54j7m75x/hJRWzlW
        zgmTdGSpLOnPeKe9TJtIkWzkqx0+XMbk1D4FUZVpo2D8whpHJxZNUdzY1UpqTu6M
        frGsQIECgYEA8vqxh7Pw3S32TyMmkpL6oNziccyKe7U+xurulmccrPD6dhpMjOXR
        0ErPBIklxiUsAEZNIdBP4G2Of1xU0OWnWH9Xpk69FI7K7/XPmOoNeC3lYp08IUtb
        jvs2C7F6ir+cSpEjU1PrT9hIKTk6XO13Nx291pd6xxUz1UUfdyxv220CgYEA639M
        jEH9BsFSghYHM41GCMp2/+xfLLN9sTdPB7b8ElsOMD2Xne1QJ9uHfXyDi5Ba07aI
        GbxgIoKcVlxIf/JJFdomeiXzf3PjDOTE8Pv/wMVhjQsfkCfgEunqVKF9amLTeTbl
        Ype2modJXe+yuo4AqN8inz3CvTsP15rfZRh9XE0CgYA6xnOdPOS9y/lx6THScOVZ
        djT8jBrPk+csnPW7whOIrf4YBYKQ7qLTPNVY5ogRpzo+ksLjtA0uX7IBkucdZQAX
        Ay7DlvZb+7KRWyeteKhrcsazFQ/PifgK3S+Uooje+TyoOPWPmZQpS0shVauNgQ++
        cF5Ug236rGFObJsQ69ne/QKBgAaxxLRL/+xcPIM0Kxo9DtubHczipEX6CD2sa9O1
        UO8YpYubhJ7Zqyim5fAcRQUHon1YOAA7SaRRgC44S1tPwOIdJHDeeVCLM84fBrYv
        A7MwKTjAMzJ+37DJ835aZN1MV+SfOeAWnftAk0ZXVQZWmRAz36EVOV71udqQLX+L
        Na0VAoGBAOyAT/XPSDjMaWMxkf0/cuGrPDotG/2qlPkFzykTurYRXfB+gs/0wM9q
        V64jR8VQpxfyljtdEEIbNnYiiHcu3WGDK6zu0w3LzYFdKawKxJezL7vbC3X4qgil
        3KsipSty93s+kZ265SMqby2itnryoMSURt5PniUFlBq5BBrzeZde
        -----END RSA PRIVATE KEY-----
      public: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDfhPP9MO+OZxmQOJaZubpnPiPHVuXitwSJKlvFhGrJe/FsaQZ75igPLLmz4z+0po/6QBgNtfAkzo2curyrhiwR6qzOMMTf6qAfnhMTwShPVWg8OSWJSITdrR3UMtlPyhfvHzL6r7f2pAU3ayNN/f1WAyltbLrM4fs6T2Gklcwi17O5f0Gww58cTdOBl1idGVz21GYjnz6KDDUTat42ocHFa7ZzgV3J2hqRNeBSZwsuF4pbTEKbQ0b0LLmgB2rv1kmu65BDFPL1bvXGbpbgSt4MwJmtHclYG8fYCG/YlwN2PwEQHaCJjPDNKozgPeXjiPNrYFQuChd/nwlL/wHsuSvJ dummmy-key-2

users:
  vagrant:
    public_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key
  admin:
    comment: "Shared Admin User"
    primary_group: default
    groups:
      - admin
    public_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDfhPP9MO+OZxmQOJaZubpnPiPHVuXitwSJKlvFhGrJe/FsaQZ75igPLLmz4z+0po/6QBgNtfAkzo2curyrhiwR6qzOMMTf6qAfnhMTwShPVWg8OSWJSITdrR3UMtlPyhfvHzL6r7f2pAU3ayNN/f1WAyltbLrM4fs6T2Gklcwi17O5f0Gww58cTdOBl1idGVz21GYjnz6KDDUTat42ocHFa7ZzgV3J2hqRNeBSZwsuF4pbTEKbQ0b0LLmgB2rv1kmu65BDFPL1bvXGbpbgSt4MwJmtHclYG8fYCG/YlwN2PwEQHaCJjPDNKozgPeXjiPNrYFQuChd/nwlL/wHsuSvJ dummmy-key-2
    uid: 1001
  bobsmith:
    comment: "Bob Smith; bobsmith@example.com"
    primary_group: default
    groups:
      - admin
    public_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key
    uid: 1002
    google_2fa:
      secret_key: JEPXZJ3HSYNHMDQO
      verification_code: 411221
      emergency_codes: [20698313,36545541,21001349,81954311,82144245]

yama_utils:
  enabled: true

ttyspy:
  common:
    ssl:
      ca_cert: |
        -----BEGIN CERTIFICATE-----
        MIIC9zCCAd+gAwIBAgIJAIE56AbnAKhuMA0GCSqGSIb3DQEBCwUAMBIxEDAOBgNV
        BAMMB3Rlc3QtY2EwHhcNMTcwNjI1MTgwOTI3WhcNMTcwODI0MTgwOTI3WjASMRAw
        DgYDVQQDDAd0ZXN0LWNhMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
        zgvi1iB4L9AGRv4sv2WnS0PizlcS98i2nVXDBYUbUGlDGxo+TdkrfsCW85GRUYei
        avEPsi4LrLWUJ4V2h5okA5N3rT+K4MFwW69RFoVYvRxzYHBcCSaDSQK9B5b+pxke
        pyFuk8VVIZDomBAndIMhVriPMDeguDALOEXPTsJZyExYU185rwXCX/eOSzcO6gqx
        MLpbZ3ErfVu2wpNgVSGxK/Isn05DbzlpRSLwT7zaO6/e0+e3oc/uC2BRNc4CUTck
        Y+UicUOS1mRgaL0Tw47pjfv1DXUVnPglUnwylRxYAkj3aWMvRJDlxUYiHszjdoJI
        S2jzgpCsEL9ZARbz3OEt7QIDAQABo1AwTjAdBgNVHQ4EFgQU9GGaMnGd9HPdCfSB
        cXx8g+jGxi8wHwYDVR0jBBgwFoAU9GGaMnGd9HPdCfSBcXx8g+jGxi8wDAYDVR0T
        BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAT9ouwn9hRMF1ffVGIyP/LkOAq53G
        nmqHKOcaVVo3Shar/Xt3jJQL5qzGsXiteQ/jnFuOVnnxMeM47SE42jHUQaxDOkO2
        VlsDaQvjk18enKeJ7Vpu9/ntO/OWN19E7sjy0uAzBfwFRnUmPGNOd27+kxjYGGA0
        h9/x7BKWdNyyA1/+lhR4EeZ6EixcQ51aJOqmgs7heLDu2DoN+t11oO3Su6M/xLJg
        Gh+MfiB46fRo72kv1MjIkysBMQuTIBv0aATLVPbhiG0VQ1ePqZ8apeDrrAJN0oPX
        BubvkaS2EzQqHlbYm4XScVH+tKNlAyLpvBdqjbAGBNNIdn1MBly3ggpobg==
        -----END CERTIFICATE-----

  client:
    enabled: true
    ssl:
      cert: |
        -----BEGIN CERTIFICATE-----
        MIIDAjCCAeqgAwIBAgIJAPqKYjM75y5YMA0GCSqGSIb3DQEBCwUAMBIxEDAOBgNV
        BAMMB3Rlc3QtY2EwHhcNMTcwNjI1MTgwOTI3WhcNMTcwODI0MTgwOTI3WjAWMRQw
        EgYDVQQDDAtzZXJ2ZXIudGVzdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
        ggEBAMidwFEci8d9jWIJpeiBkW2crSfog9aW6HQWNJXeaL8CY7jLsn6OyzeV2/Rz
        BpssxvBYkKghnvg6/0x1Nj7nylUlgc7UrmhZ83oWg01UGwZnMGDRVlYaMz4lEMDk
        XbCRtrYmq0M5ZlYAI10FdCI3U+a/JjQBV7jiV3I4lRkiaNTEZyGFqNeJdmMJ41dg
        COnU2w/cJkAtQ+3KQB6ud+oUbR9Ixjxicu7Wi8JV7oeDY8ofYWXYXgnc+M9zfvye
        2fEhJO5aV8xCKaJzNgBgZZZhcJMar3nW4Fd8ogehioghnbLhmHkxQSI96fYiteCd
        vtoqSbQ7g05G/vbfl0NgJgA83DkCAwEAAaNXMFUwCQYDVR0TBAIwADALBgNVHQ8E
        BAMCBeAwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBwGA1UdEQQVMBOC
        C3NlcnZlci50ZXN0hwSsEACYMA0GCSqGSIb3DQEBCwUAA4IBAQCdTqbyjAeCL38/
        5zDNnQokO+LVMaMMsCxNHIusWSpWMlepgPP5iGIZ+aWo4LspGwMFDjGoYc3mxGx3
        unq2GBLhnw04gNFktzmTo24jaDWxt/irrNRY9B+Q//l5rZOXTbbYHuFrauCvxogN
        ludljzM/W79Y0rwpkh6nc9A8OoTeSfntbp8cuzjwgkPb2Q+JR8QYU+0isble9K9h
        kjmKFitWl1tQY1RkkAwDSF7jA9w6olyp1/VVTpAEbBBpKKioXzQ4B/2lE7da/dSn
        Vwx7cO4H4RZ8V1q4fKR8KRDLQ0hMvaIX14+LtApu8t1Dj2lweBGWmrEulksdxxbm
        TA/q0ryr
        -----END CERTIFICATE-----
      key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEpgIBAAKCAQEAyJ3AURyLx32NYgml6IGRbZytJ+iD1pbodBY0ld5ovwJjuMuy
        fo7LN5Xb9HMGmyzG8FiQqCGe+Dr/THU2PufKVSWBztSuaFnzehaDTVQbBmcwYNFW
        VhozPiUQwORdsJG2tiarQzlmVgAjXQV0IjdT5r8mNAFXuOJXcjiVGSJo1MRnIYWo
        14l2YwnjV2AI6dTbD9wmQC1D7cpAHq536hRtH0jGPGJy7taLwlXuh4Njyh9hZdhe
        Cdz4z3N+/J7Z8SEk7lpXzEIponM2AGBllmFwkxqvedbgV3yiB6GKiCGdsuGYeTFB
        Ij3p9iK14J2+2ipJtDuDTkb+9t+XQ2AmADzcOQIDAQABAoIBAQCpIfYFbB+cLAmK
        Yb/x6WqGEtUZFDoyLEAFvsLOpxeAEa+pGHJ/qDtDvaAW0vL62CFQeBpc5Rt1A6hA
        +YCmQByg9GIf0cbISy2t/FTuWL4AA/cRaOt049nXxr/9H4qtVevIXYl9v2K7lpo5
        zmM+hY7Cttyqc4dVY919ep6Y9h2TYhFlTeoxWsjkOMC94m+1337JvCfFBC2KONuU
        H7OD08lE9TIXOpv94vWBvnCBUxnwOCZ0bQUr1qS3rWwcP/CNEL3KRCp8BS4VQnBb
        KLxzpQ9f9LYq1VmBop358I6UWBafb0pIzF1FcdKG5Ma/L/Q4+AdGND4QjgyEL/fp
        U82FnfjRAoGBAP0/hSUfORh1gxR1EnuJJGn6HuKufLWOXgnSKkNMZ8feKK60hyYe
        btcZlkh1RHiI3j9DX1PocIjEEzUtgDY13JcxoqpHmSY+KvLPb0D5bkk6zTSr/kJH
        QUTrXcS4BUiy8YOA1LyOlhNiVZ1C9UtYj8GSx8Hm17woB4qIqgJEPuxLAoGBAMrL
        0iWJjMshZMIQtsuXqZ5RpMsF97ZIQ3e3fmgCxs8108H/aVe1l6KyepVWOkVBbhnn
        OXHNOlI2sm3Bf1xpLY8mek+I/6DD0Z+gsUd47sQOuaYGmOYDpbDcEoJGBoXuBpxD
        OTiQP+wcFFlVjRSOWnYM5qkVrxDn9EtBK/E+Pv8LAoGBALRdjSKHPk7hQt5LE0LQ
        xhKEhYLE6yUTpH4yJM+Rl0iOPUNQaAEKI78nBhXND1sZf9Bm13oXTi7aFyQEqA/0
        BIvaWhQUskq+dDBC9OW9wIJ/Uq90372sqhu/1iTJO1ovuDsEgn9YviJIItnCWpmz
        FY+0TnkXRAdKKzTLaOn8WSRJAoGBALefmDeO9aIUKZSi57EvMVF+IZYHYEV350cm
        Kdnp8bQ7y/LT3sGhVpzluKMxwW9mEFh6CoSlzFIW3rcMxtKZFbyRnZwYs0YRKOS9
        7ueFc8SohKb1QEq9MLEUg9nbqBpq7Sdeoxg5XPfgcPh2w1jCkNxlUBH35V2MeaIO
        b8hvkUEDAoGBAJebZ3xwbaQWc7mmHq4rrFTIkaM1BMBFoU23kXi8dDcR1whNAal0
        /PqZyNduxrZpFJ31q4/ZhT7sSS6JnKft9xliyh3a2zRdc2cn2NYWhDxKyiGsLCph
        DAuubrT+HoMApzxGbIV+f6afRafKViJf17giVa77hWHIjNMg+vOPwqdz
        -----END RSA PRIVATE KEY-----
  server:
    enabled: true
    host: server.test
    ip: 172.16.0.152
    port: 8090
    transcript_path: /tmp/transcripts
    firewall:
      friendly_networks:
        - "{{ private_ipv4.network }}/{{ private_ipv4.netmask }}"
        - "{{ public_ipv4.network }}/{{ public_ipv4.netmask }}"
    ssl:
      cert: |
        -----BEGIN CERTIFICATE-----
        MIIDAjCCAeqgAwIBAgIJAPqKYjM75y5YMA0GCSqGSIb3DQEBCwUAMBIxEDAOBgNV
        BAMMB3Rlc3QtY2EwHhcNMTcwNjI1MTgwOTI3WhcNMTcwODI0MTgwOTI3WjAWMRQw
        EgYDVQQDDAtzZXJ2ZXIudGVzdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
        ggEBAMidwFEci8d9jWIJpeiBkW2crSfog9aW6HQWNJXeaL8CY7jLsn6OyzeV2/Rz
        BpssxvBYkKghnvg6/0x1Nj7nylUlgc7UrmhZ83oWg01UGwZnMGDRVlYaMz4lEMDk
        XbCRtrYmq0M5ZlYAI10FdCI3U+a/JjQBV7jiV3I4lRkiaNTEZyGFqNeJdmMJ41dg
        COnU2w/cJkAtQ+3KQB6ud+oUbR9Ixjxicu7Wi8JV7oeDY8ofYWXYXgnc+M9zfvye
        2fEhJO5aV8xCKaJzNgBgZZZhcJMar3nW4Fd8ogehioghnbLhmHkxQSI96fYiteCd
        vtoqSbQ7g05G/vbfl0NgJgA83DkCAwEAAaNXMFUwCQYDVR0TBAIwADALBgNVHQ8E
        BAMCBeAwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBwGA1UdEQQVMBOC
        C3NlcnZlci50ZXN0hwSsEACYMA0GCSqGSIb3DQEBCwUAA4IBAQCdTqbyjAeCL38/
        5zDNnQokO+LVMaMMsCxNHIusWSpWMlepgPP5iGIZ+aWo4LspGwMFDjGoYc3mxGx3
        unq2GBLhnw04gNFktzmTo24jaDWxt/irrNRY9B+Q//l5rZOXTbbYHuFrauCvxogN
        ludljzM/W79Y0rwpkh6nc9A8OoTeSfntbp8cuzjwgkPb2Q+JR8QYU+0isble9K9h
        kjmKFitWl1tQY1RkkAwDSF7jA9w6olyp1/VVTpAEbBBpKKioXzQ4B/2lE7da/dSn
        Vwx7cO4H4RZ8V1q4fKR8KRDLQ0hMvaIX14+LtApu8t1Dj2lweBGWmrEulksdxxbm
        TA/q0ryr
        -----END CERTIFICATE-----
      key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEpgIBAAKCAQEAyJ3AURyLx32NYgml6IGRbZytJ+iD1pbodBY0ld5ovwJjuMuy
        fo7LN5Xb9HMGmyzG8FiQqCGe+Dr/THU2PufKVSWBztSuaFnzehaDTVQbBmcwYNFW
        VhozPiUQwORdsJG2tiarQzlmVgAjXQV0IjdT5r8mNAFXuOJXcjiVGSJo1MRnIYWo
        14l2YwnjV2AI6dTbD9wmQC1D7cpAHq536hRtH0jGPGJy7taLwlXuh4Njyh9hZdhe
        Cdz4z3N+/J7Z8SEk7lpXzEIponM2AGBllmFwkxqvedbgV3yiB6GKiCGdsuGYeTFB
        Ij3p9iK14J2+2ipJtDuDTkb+9t+XQ2AmADzcOQIDAQABAoIBAQCpIfYFbB+cLAmK
        Yb/x6WqGEtUZFDoyLEAFvsLOpxeAEa+pGHJ/qDtDvaAW0vL62CFQeBpc5Rt1A6hA
        +YCmQByg9GIf0cbISy2t/FTuWL4AA/cRaOt049nXxr/9H4qtVevIXYl9v2K7lpo5
        zmM+hY7Cttyqc4dVY919ep6Y9h2TYhFlTeoxWsjkOMC94m+1337JvCfFBC2KONuU
        H7OD08lE9TIXOpv94vWBvnCBUxnwOCZ0bQUr1qS3rWwcP/CNEL3KRCp8BS4VQnBb
        KLxzpQ9f9LYq1VmBop358I6UWBafb0pIzF1FcdKG5Ma/L/Q4+AdGND4QjgyEL/fp
        U82FnfjRAoGBAP0/hSUfORh1gxR1EnuJJGn6HuKufLWOXgnSKkNMZ8feKK60hyYe
        btcZlkh1RHiI3j9DX1PocIjEEzUtgDY13JcxoqpHmSY+KvLPb0D5bkk6zTSr/kJH
        QUTrXcS4BUiy8YOA1LyOlhNiVZ1C9UtYj8GSx8Hm17woB4qIqgJEPuxLAoGBAMrL
        0iWJjMshZMIQtsuXqZ5RpMsF97ZIQ3e3fmgCxs8108H/aVe1l6KyepVWOkVBbhnn
        OXHNOlI2sm3Bf1xpLY8mek+I/6DD0Z+gsUd47sQOuaYGmOYDpbDcEoJGBoXuBpxD
        OTiQP+wcFFlVjRSOWnYM5qkVrxDn9EtBK/E+Pv8LAoGBALRdjSKHPk7hQt5LE0LQ
        xhKEhYLE6yUTpH4yJM+Rl0iOPUNQaAEKI78nBhXND1sZf9Bm13oXTi7aFyQEqA/0
        BIvaWhQUskq+dDBC9OW9wIJ/Uq90372sqhu/1iTJO1ovuDsEgn9YviJIItnCWpmz
        FY+0TnkXRAdKKzTLaOn8WSRJAoGBALefmDeO9aIUKZSi57EvMVF+IZYHYEV350cm
        Kdnp8bQ7y/LT3sGhVpzluKMxwW9mEFh6CoSlzFIW3rcMxtKZFbyRnZwYs0YRKOS9
        7ueFc8SohKb1QEq9MLEUg9nbqBpq7Sdeoxg5XPfgcPh2w1jCkNxlUBH35V2MeaIO
        b8hvkUEDAoGBAJebZ3xwbaQWc7mmHq4rrFTIkaM1BMBFoU23kXi8dDcR1whNAal0
        /PqZyNduxrZpFJ31q4/ZhT7sSS6JnKft9xliyh3a2zRdc2cn2NYWhDxKyiGsLCph
        DAuubrT+HoMApzxGbIV+f6afRafKViJf17giVa77hWHIjNMg+vOPwqdz
        -----END RSA PRIVATE KEY-----

support_tools:
  enabled: false

sshagentmux:
  enabled: true
  auth_socket: /var/run/authorization_proxy.sock

logging:
  enabled: false
sensu:
  client:
    enabled: false
