---
- name: remove pxelinux.cfg directory
  file:
    path: "{{ pxe.tftpboot_path }}/pxelinux.cfg"
    state: absent

- name: remove server preseeds directory
  file:
    path: "{{ pxe.tftpboot_path }}/servers"
    state: absent

- name: remove tftp config
  file:
    path: /etc/dnsmasq.d/pxeboot.conf
    state: absent

- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted
