jenkins:
  apt:
    pkgs:
      - libxml2-dev
      - libxslt1-dev
      - python-dev
      - jenkins=1.*
  plugins:
    - name: ansicolor
      version: '0.4.2'
    - name: antisamy-markup-formatter
      version: '1.1'
    - name: ant
      version: '1.2'
    - name: build-timeout
      version: '1.16'
    - name: conditional-buildstep
      version: '1.3.3'
    - name: copyartifact
      version: '1.38'
    - name: cvs
      version: '2.11'
    - name: envinject
      version: '1.92.1'
    - name: external-monitor-job
      version: '1.4'
    - name: gerrit-trigger
      version: '2.21.1'
    - name: ghprb
      version: '1.32.2'
    - name: git-client
      version: '1.19.6'
    - name: github-api
      version: '1.75'
    - name: github
      version: '1.19.1'
    - name: github-oauth
      version: '0.23'
    - name: git
      version: '2.4.4'
    - name: icon-shim
      version: '2.0.3'
    - name: javadoc
      version: '1.1'
    - name: jenkins-multijob-plugin
      version: '1.21'
    - name: ldap
      version: '1.11'
    - name: mapdb-api
      version: '1.0.6.0'
    - name: matrix-auth
      version: '1.1'
    - name: maven-plugin
      version: '2.7.1'
    - name: notification
      version: '1.10'
    - name: pam-auth
      version: '1.1'
    - name: parameterized-trigger
      version: '2.30'
    - name: plain-credentials
      version: '1.1'
    - name: postbuildscript
      version: '0.17'
    - name: postbuild-task
      version: '1.8'
    - name: random-string-parameter
      version: '1.0'
    - name: run-condition
      version: '1.0'
    - name: scm-api
      version: '1.2'
    - name: script-security
      version: '1.13'
    - name: slack
      version: '1.8.1'
    - name: ssh-agent
      version: '1.10'
    - name: ssh
      version: '2.4'
    - name: ssh-slaves
      version: '1.9'
    - name: structs
      version: '1.1'
    - name: subversion
      version: '1.54'
    - name: throttle-concurrents
      version: '1.9.0'
    - name: timestamper
      version: '1.7.4'
    - name: token-macro
      version: '1.12.1'
    - name: translation
      version: '1.10'
    - name: windows-slaves
      version: '1.0'
    - name: workflow-step-api
      version: '2.0'
    - name: ws-cleanup
      version: '0.29'
    - name: jquery
      version: '1.7.2-1'
    - name: nodelabelparameter
      version: '1.7.2'
    - name: graphiteIntegrator
      version: '1.2'
  stackrc: ''
  jjb:
    git:
      source:
        repo: https://github.com/blueboxgroup/jenkins-job-builder.git
        rev: master
        path: /usr/local/src/jjb
      jobs:
        repo: https://{{secrets.jjb.user}}:{{secrets.jjb.password}}@github.com/notreal/jenkins-job-builder.git
        rev: master
        path: /var/lib/jenkins/jjb-jobs
        key_file: /var/lib/jenkins/.ssh/ghe
  port: 8080
  host: 127.0.0.1
  url: http://jenkins.example.com/
  prefix: ""
  slack:
    teamdomain: ~
    token: ~
    room: ~
    buildserverurl: http://jenkins.example.com/
  apache:
    enabled: True
    github_hooks_only: False
    port: 80
    host: 0.0.0.0
    allow_from:
      - 0.0.0.0/0
    servername: jenkins.example.com
    basicauth:
      enabled: False
      username: ~
      password: ~
    ssl:
      port: 443
      intermediate: ~
      cert: |
        -----BEGIN CERTIFICATE-----
        MIIDbjCCAlagAwIBAgIJANyptbhIpO8TMA0GCSqGSIb3DQEBCwUAMEUxCzAJBgNV
        BAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5ldCBX
        aWRnaXRzIFB0eSBMdGQwHhcNMTUwMTE0MTg0MTQyWhcNMTYwMTE0MTg0MTQyWjBF
        MQswCQYDVQQGEwJBVTETMBEGA1UECAwKU29tZS1TdGF0ZTEhMB8GA1UECgwYSW50
        ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
        CgKCAQEA1MWu8kJ20FCLbBIMqgTlKCOL54X06C0bERm3wIOwu6dk35s7uy78I2pt
        dA2sbwLeIMiJHKY85eBNI+pMZGNsRYajl3BZRvSWcjO6DHGN8k0ljf6gvzAlzyG0
        2Pz0Th1R2fveOE0fNZcT/JqbKLFb/Cu3GoaC/wUAbRK36qgzQkX4hQD0QVylhdmS
        82Fsr6H4fl7iybn7w1HwA2DG4MuJRjCeskujfz0ch7/BBdON84SDVGcemHkO45R/
        c6n49jnTHiJ5CJXsZz4uH8lEs0Q6CW2GMtVbPiXfJ8TLBdSgMp6atVMCMNsa0Pg1
        I5hXAqknZf9Uc3KWdBRkufJrwHnFuwIDAQABo2EwXzAPBgNVHREECDAGhwSsEAAN
        MB0GA1UdDgQWBBQzjGYx1ss5NQuRGAf3nk7KenvLyTAfBgNVHSMEGDAWgBQzjGYx
        1ss5NQuRGAf3nk7KenvLyTAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IB
        AQBAcq4Fe5+5jeRBqS0R9EApBeQZfCV+h88UpzAsWWhxicft1BUiftMzAwAE0VnG
        xTB96jmlmHXjSR8ugCED4A6wkjW3mDo5SmkWLQBCY1EHSUdIgVbhK4zxP4TLhGbD
        54+nGAsRLM1Hb5UlI1uCa4E/1gdeLUd41vSfKc8/A133Rl1CMpFLHuMgE1VgVQkU
        ElkHVD8xQlOrza/yMT1eGg4tbR4ukqjdC4vOWqGPmajlR+gk/sJ2Ut1CzN4fcmtj
        yqcwxri9aiDB1mimS+m/SjKvPf6lV5bDRtQWXbCPAWzq8gKvv2PqoNyyZOxbqJhM
        eb0+9ULVAGAYtcZuNHgs0bH+
        -----END CERTIFICATE-----
      key: |
        -----BEGIN PRIVATE KEY-----
        MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDUxa7yQnbQUIts
        EgyqBOUoI4vnhfToLRsRGbfAg7C7p2Tfmzu7Lvwjam10DaxvAt4gyIkcpjzl4E0j
        6kxkY2xFhqOXcFlG9JZyM7oMcY3yTSWN/qC/MCXPIbTY/PROHVHZ+944TR81lxP8
        mpsosVv8K7cahoL/BQBtErfqqDNCRfiFAPRBXKWF2ZLzYWyvofh+XuLJufvDUfAD
        YMbgy4lGMJ6yS6N/PRyHv8EF043zhINUZx6YeQ7jlH9zqfj2OdMeInkIlexnPi4f
        yUSzRDoJbYYy1Vs+Jd8nxMsF1KAynpq1UwIw2xrQ+DUjmFcCqSdl/1RzcpZ0FGS5
        8mvAecW7AgMBAAECggEAeP6BYdpR3lwvLKGG+hgWiCDOqjYO8wjTX4IUcDFzCwNB
        5bZM3UD2uN0IqPotmGM1Fcdz0QrnjoFi3I2cK2ouY8sQtEl7O1JTS1YG8pSQd71P
        IdQubQpgNc2hHdOayeD6bs8/qxyQJtVm1DrHCPjyqg/h6/+Z9pNNjrkaRSKpI4HF
        Jtuj8iRHV9yWDoNU1eWO6qzoEU1fNE48XVefpLpVDJx0u4Ih8/BHguTBH1DO5qQt
        sNkBUNh09Fy3ZqM2085ZMmi+W+EqtNJyYsB7J2324Bga7Voo71s9HNDZWLWHTIYW
        jaPBRvn4mjlVua1o8Dd3/RQ2JVzwiv/aZ47IGw3cgQKBgQDwco2IduJkWHnOyPKZ
        +uo4xmYBa8UswBMqmfPaTijZ4naG9J34LjZFtvsJhSqOrdKEYbP3ONz3UwvOFUQg
        kzC/F5TJidDzNXPiLd+3NpssofnVwLKdZUwORkLoBph7oAY2fImaoWIGfPsHyam5
        o4RWbsyhxKozFyBn2NBIyxQ0EQKBgQDiiN6rsHusVdH5OreO6Z8RvB9ULUH8seB+
        f1oYiHSfPZQ4fkwsB8k9gF6yJOb/Kob3FSoc5GRpd4TK9DXHTZh41Q3/CSwveYYa
        5BJlupXGgAzu6vFuyUxAw/TclZFD9uAjrlfu8lbRpBHzKZtJnJQtgNPFflH6ZxbY
        ljlNO4f5CwKBgA42l0szy9omqLyigES94k6M28bFuhgVGozwIMwMxrlqe5sqppPf
        F3IziM9dQdDBUaplpB+/CsDL9eyusSJD0SPanv7y2Jkn1bvO/mR0I+QVhxEtnOFU
        9ZP6b0YL7cORCAz8e53aYFMF3EjvkMracZ4yWoJNf8oZWd8Jn/ZNmtohAoGAN/yF
        s78BQb1QEJ2PYhWhB5wLzh0FUvOPPRQyax/GWti4OiIUp0khVj7UqIhwQp37DzO+
        3bcgjeRJAHPMmr41sZ9OPzrAHdeV6i110oiDnbRl/eI42x2K5/LGIIIijb6E9KyQ
        9PAVvugiu4sL4ux8vqY5MHUgw5cY0VyHOuw8lbMCgYBPZtqsJs+zrkZj9HD+lQvo
        N2CQtonrnIwqaorgbZVr1PDBJo0AHBraQRt/0Xpzu4Q/rjkHxlhESjW17Ax3JS1s
        gRwuu+SIjud/7fZcGy8to7MbdJrWiYFUOlQF6F/kEIq3bsHmJWbi1FgTdeQkkEl6
        DFeUkc2q0uaO1lZIAnMA4w==
        -----END PRIVATE KEY-----
  git:
    email: jenkins@bluebox.net
    name: Leeroy Jenkins
  security:
    github:
      orgs:
        - blueboxgroup
      admins: []
      web_uri: https://github.com
      api_uri: https://api.github.com
      client_id: ''
      client_secret: ''
    credentials: []
  configuration_templates:
    - config.xml
    - credentials.xml
    - github-plugin-configuration.xml
    - jenkins.model.JenkinsLocationConfiguration.xml
    - jenkins.plugins.slack.SlackNotifier.xml
    - gerrit-trigger.xml
    - com.tikal.jenkins.plugins.multijob.PhaseJobsConfig.xml
  github_servers: []
  github_pull_config: []
  gerrit_servers: []
  slave:
    apt:
      - libssl-dev
    pip:
      - python-keystoneclient
      - python-swiftclient
    gem:
      - package_cloud
  ssh_keys: []
  multijob:
    retry:
      rules:
        - name: multijob-failure-retry-rule
          path: /var/lib/jenkins/failure.prop
  master_mode_exclusive: true
  logrotate:
    frequency: weekly
    rotations: 90
  packagecloud:
    token: "thisisbadtoken"
