---
- name: create netdata user
  user: name=netdata comment=netdata shell=/bin/false
        system=yes home=/nonexistent

- name: netdata defaults
  lineinfile:
    dest: /etc/default/netdata
    line: "{{ item }}"
    create: true
    mode: 0644
  with_items:
    - 'PIDFILE="/var/run/netdata.pid"'
    - 'EXTRA_OPTS="-P /var/run/netdata.pid"'

- include: ./roles/_cuttle/tasks/install_deb.yml
  vars:
    package_name: netdata
    package_url: "{{ netdata.package }}"

- name: ensure netdata service is running
  service:
    name: netdata
    enabled: true
    state: started

- name: allow access to netdata web
  ufw: rule=allow to_port=19999 proto=tcp src={{ item }}
  with_items: "{{ netdata.firewall.allow_from }}"
  tags:
    - firewall

- name: configure metrics backend
  ini_file:
    path: /etc/netdata/netdata.conf
    section: "{{ item.0 }}"
    option: "{{ item.1|regex_replace('_',' ') }}"
    value: "{{ item.2 }}"
    backup: yes
  with_inidata: "{{ netdata.config }}"

- meta: flush_handlers

- include: checks.yml
  when: sensu.client.enable_checks|default('True')|bool
  tags: sensu-checks

- include: metrics.yml
  when: sensu.client.enable_metrics|default('True')|bool
  tags: sensu-metrics

- include: serverspec.yml
  when: serverspec.enabled|default("True")|bool
  tags: serverspec
