---
- name: always update these packages
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: latest
  register: result
  until: result|succeeded
  retries: 5
  with_items: "{{ security.always_update.apt }}"
  tags: skip_ansible_lint

- include: checks.yml
  when: sensu.client.enable_checks|default('True')|bool
  tags: sensu-checks

- include: metrics.yml
  when: sensu.client.enable_metrics|default('True')|bool
  tags: sensu-metrics

- include: serverspec.yml
  when: serverspec.enabled|default("True")|bool
  tags: serverspec
