---
# It is recommended that this role be played with serial set to 1 because
# There is a bug with initializing multiple nodes in the HA cluster at once
# http://rabbitmq.1065348.n5.nabble.com/Rabbitmq-boot-failure-with-quot-tables-not-present-quot-td24494.html

- name: add rabbitmq erlang cookie
  template: 
    src: var/lib/rabbitmq/erlang.cookie
    dest: /var/lib/rabbitmq/.erlang.cookie
    owner: rabbitmq 
    group: rabbitmq 
    mode: 0400
  register: erlang_cookie

- name: add rabbitmq cluster configuration
  template: 
    src: etc/rabbitmq/rabbitmq.config 
    dest: /etc/rabbitmq/rabbitmq.config
    owner: rabbitmq
    group: rabbitmq 
    mode: 0600
  register: cluster_configuration

# When rabbitmq starts it creates  '/var/lib/rabbitmq/mnesia'. This dir
# should be deleted before clustering is setup because it retains data that
# can conflict with the clustering information.
- name: remove mnesia configuration
  file: path=/var/lib/rabbitmq/mnesia state=absent
  when: erlang_cookie.changed or 
        cluster_configuration.changed

- name: stop rabbit cluster
  service: name=rabbitmq-server state=stopped
  when: erlang_cookie.changed or
        cluster_configuration.changed

  # In case there are lingering processes, ignore errors silently
- name: send sigterm to any running rabbitmq processes
  command: killall -u rabbitmq
  failed_when: false
  when: erlang_cookie.changed or
        cluster_configuration.changed

- name: start rabbitmq
  service: name=rabbitmq-server state=started enabled=yes

- name: wait for rabbit to start
  wait_for: port={{ rabbitmq.port }} host={{ rabbitmq.ip }} delay=2

- name: set the HA mirror queues policy
  rabbitmq_policy: name=HA
    node={{ rabbitmq.nodename }}
    pattern='.*'
    tags=ha-mode=all

- meta: flush_handlers
