---
- name: start sensu
  service:
    name: "{{ item }}"
    state: started
    must_exist: false
  with_items:
    - sensu-api
    - sensu-server

- name: stop sensu
  service:
    name: "{{ item }}"
    state: stopped
    must_exist: true
  with_items:
    - sensu-api
    - sensu-server

- name: kill sensu
  shell: "cat /var/run/sensu/sensu*-{{ item }}.pid | xargs -r -I% kill -9 %"
  with_items:
    - api
    - server

- name: restart sensu
  service:
    name: "{{ item }}"
    state: restarted_if_running
    must_exist: true
  with_items:
    - sensu-api # need this up before sensu-server gets restarted
    - sensu-server

- name: restart sensu dashboard
  service:
    name: uchiwa
    state: restarted_if_running
    must_exist: true
