---
- name: jjb source repo
  git: repo="{{ jenkins.jjb.git.source.repo }}"
       dest="{{ jenkins.jjb.git.source.path }}"
       version="{{ jenkins.jjb.git.source.rev }}"
       update=true
       force=true
       accept_hostkey=true

- name: jjb jobs repo
  git: repo="{{ jenkins.jjb.git.jobs.repo }}"
       dest="{{ jenkins.jjb.git.jobs.path }}"
       version="{{ jenkins.jjb.git.jobs.rev }}"
       update=true
       force=true
  become: yes
  become_user: jenkins

- name: install jenkins job builder
  pip: name="{{ jenkins.jjb.git.source.path }}"

- name: create jjb config directory
  file: dest=/etc/jenkins_jobs state=directory mode=0755

- name: configure jenkins job builder
  template: src=etc/jenkins_jobs/jenkins_jobs.ini dest=/etc/jenkins_jobs/jenkins_jobs.ini
            owner=root group=jenkins mode=0640

- name: install the job loading script
  copy: src=usr/local/bin/load-jenkins-jobs.sh dest=/usr/local/bin/load-jenkins-jobs.sh mode=0755

- name: seed the jenkins jobs
  shell: "/usr/local/bin/load-jenkins-jobs.sh /etc/jenkins_jobs/jenkins_jobs.ini {{ jenkins.jjb.git.jobs.path }}/servers/{{ hostname }}"
