---
ipsec:
  implementation:
    package: strongswan
    service: strongswan
  nat_enabled: False
  config:
    nat_traversal: "yes"
    virtual_private: "%v4:{{ hostvars['ipsec-client'][private_interface]['ipv4']['network'] }}/{{ hostvars['ipsec-client'][private_interface]['ipv4']['netmask'] }}"
  connections:
    example:
      authby: "secret"
      auto: "start"
      compress: "no"
      dpdaction: restart
      dpddelay: 30
      dpdtimeout: 120
      esp: "aes256-sha256-modp2048"
      forceencaps: "yes"
      ike: "aes256-sha256-modp2048"
      ikelifetime: 86400s
      keyingtries: "%forever"
      keylife: 3600s
      leftupdown: "/etc/ipsec.d/ipsec-notify.sh"
      mark: 500
      type: "tunnel"
      rekeymargin: 540s
      rekey: "yes"
      left: "{{ hostvars['ipsec-client'][public_interface]['ipv4']['address'] }}"
      leftsubnet: "{{ hostvars['ipsec-client'][private_interface]['ipv4']['network'] }}/{{ hostvars['ipsec-client'][private_interface]['ipv4']['netmask'] }}"
      left_vti_ip: "169.254.0.1"
      right: "{{ hostvars['ipsec-server'][public_interface]['ipv4']['address'] }}"
      rightsubnet: "{{ hostvars['ipsec-server'][private_interface]['ipv4']['network'] }}/{{ hostvars['ipsec-server'][private_interface]['ipv4']['netmask'] }}"
      right_vti_ip: "169.254.0.2"
  sharedkeys:
    example:
      remote_ip:  "{{ hostvars['ipsec-server'][public_interface]['ipv4']['address'] }}"
      key: "dfgffk4ltjk3jkl234t234t"
