logging:
  enabled: true
  service:
    user: logstash
    group: adm
    home: /var/lib/logstash
  follow:
    enabled: true
    global_fields:
      customer_id: "unknown"
      cluster_name: "unknown"
    logs: []
  forward:
    host: null
    filebeat:
      version: 1.3.1
      port: 4561
      config_dir: /etc/filebeat/filebeat.d
    tls:
      enabled: false
      ca_cert: ~
