---
- name: enable apache mods for gem-mirror
  apache2_module: name={{ item }}
  with_items:
    - proxy_http
    - rewrite
    - headers

- name: add gem_mirror apache vhost
  template: src=etc/apache2/sites-available/gem_mirror
            dest=/etc/apache2/sites-available/gem_mirror.conf
  notify:
    - restart apache

- name: enable gem_mirror vhost
  apache2_site: state=enabled name=gem_mirror
  notify:
    - restart apache

- meta: flush_handlers

- name: ensure apache is running
  service: name=apache2 state=started enabled=yes
