---
dependencies:
  - role: apt-repos
    repos:
      - repo: 'deb {{ apt_repos.percona.repo }} {{ ansible_distribution_release }} main'
        key_url: '{{ apt_repos.percona.key_url }}'
  - role: logging-config
    service: percona
    logdata: "{{ percona.logs }}"
    forward_type: "{{ percona.logging.forwarder }}"
    when: logging.enabled|default("True")|bool
  - role: sensu-check
