---
- name: include vars from sensu-common
  include_vars:
    file: ../sensu-common/defaults/main.yml

- name: sensu checks directory
  file: dest=/etc/sensu/conf.d/checks
        state=directory mode=0755
