---
common:
  firewall:
    friendly_networks: []
  sysdig:
    enabled: False

sensu:
  enabled: False

collectd:
  enabled: False

netdata:
  enabled: true
  firewall:
    allow_from:
      - any

apache:
  listen:
    - 80
