---
actions:
  1:
    action: delete_indices
    description: Delete indices older than specified number of days.
    filters:
    - filtertype: pattern
      kind: prefix
      value: logstash-
      exclude:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: {{ older_than }}
      exclude:
