---
- name: install mod_auth_openidc deps
  apt: pkg=ssl-cert

- name: download mod_auth_openidc
  get_url: url={{ openid_proxy.download.url }}
           dest=/tmp/libapache2-mod-auth-openidc_{{ openid_proxy.version }}-1_amd64.deb
  when: openid_proxy.oidc.enabled|bool

- name: install mod_auth_openidc
  apt: deb=/tmp/libapache2-mod-auth-openidc_{{ openid_proxy.version }}-1_amd64.deb
       install_recommends=yes
  notify: restart apache
  when: openid_proxy.oidc.enabled|bool

- name: enable apache mod auth_openidc
  apache2_module: name=auth_openidc
  when: openid_proxy.oidc.enabled|bool
  notify: restart apache

# if auth_openidc.conf.dpkg-dist exists, it is because we upgraded the package
# and we need to overwrite our custom config with the new one.
- name: overwrite old module config if new is installed
  command: mv /etc/apache2/mods-available/auth_openidc.conf.dpkg-dist /etc/apache2/mods-available/auth_openidc.conf
  args:
    creates: /etc/apache2/mods-available/auth_openidc.conf
    removes: /etc/apache2/mods-available/auth_openidc.conf.dpkg-dist
  notify: restart apache

# if mod auth_openidc is enabled but not configured or used by any sites
# it blocks apache start
- name: configure default auth provider
  lineinfile: dest=/etc/apache2/mods-available/auth_openidc.conf
              line="OIDCProviderIssuer auth.bluebox.net"
  notify: restart apache
  when: openid_proxy.oidc.enabled|bool

- name: enable apache mod ssl
  apache2_module: name=ssl
  notify: restart apache
  when: openid_proxy.apache.ssl.enabled

- name: enable apache mod header
  apache2_module: name=headers
  notify: restart apache

- name: enable apache mod proxy_http
  apache2_module: name=proxy_http
  notify: restart apache

- name: enable apache mod status
  apache2_module: name=status
  when: openid_proxy.apache_status

- name: install apache template
  template: src=etc/apache2/sites-available/openid_proxy.conf
            dest=/etc/apache2/sites-available/{{ openid_proxy.vhost_name }}.conf
  notify: restart apache

- name: install redirect template
  template:
    src: etc/apache2/sites-available/redirect.conf
    dest: "/etc/apache2/sites-available/redirect-{{ item.name }}.conf"
  with_items: "{{ openid_proxy.apache.redirects }}"
  notify: restart apache

- name: install admin apache template
  template: src=etc/apache2/sites-available/admin_proxy.conf
            dest=/etc/apache2/sites-available/admin_{{ openid_proxy.vhost_name }}.conf
  notify: restart apache

- name: admin users
  htpasswd: name={{ item.username }} password={{ item.password }}
            path=/etc/apache2/openid_admin_passwd
  with_items: "{{ openid_proxy.admin.users }}"

- name: install apache location index
  template: src=var/www/html/index.html
            dest=/var/www/html/index.html

- name: install apache healthcheck file
  template: src=var/www/html/health_check
            dest=/var/www/html/health_check
  when: openid_proxy.health_check_enabled|default('False')|bool

- name: enable site
  apache2_site: name={{ openid_proxy.vhost_name }}.conf state={{ openid_proxy.apache.state }}
  notify: restart apache

- name: enable redirects
  apache2_site:
    name: "redirect-{{ item.name }}.conf"
    state: "{{ item.state }}"
  with_items: "{{ openid_proxy.apache.redirects }}"
  notify: restart apache

- name: enable admin site
  apache2_site: name=admin_{{ openid_proxy.vhost_name }}.conf state={{ openid_proxy.admin.apache.state }}
  notify: restart apache

- name: allow openid_proxy traffic
  ufw: rule=allow to_port={{ item.0.port }} src={{ item.1|default('127.0.0.1') }}
  with_subelements:
    - "{{ openid_proxy.firewall }}"
    - src
  tags:
    - firewall

- meta: flush_handlers

- name: ensure apache is running
  service: name=apache2 state=started enabled=yes

- include: checks.yml
  when: sensu.client.enable_checks|default('True')|bool
  tags: sensu-checks

- include: metrics.yml
  when: sensu.client.enable_metrics|default('True')|bool
  tags: sensu-metrics

- include: serverspec.yml
  when: serverspec.enabled|default("True")|bool
  tags: serverspec
