---
apache:
  modules:
    - libapache2-mod-wsgi
  listen: []
  logs:
    # See logging-config/defaults/main.yml for filebeat vs. logstash-forwarder example
    - paths:
        - /var/log/apache2/access.log
      fields:
        tags: apache_access
    - paths:
        - /var/log/apache2/error.log
      fields:
        tags: apache_error
  logging:
    forwarder: filebeat
  ssl:
    settings: |
      SSLEngine on
      SSLProtocol All -SSLv2 -SSLv3
      SSLHonorCipherOrder On
      SSLCompression off
      # Add six earth month HSTS header for all users...
      Header always set Strict-Transport-Security "max-age=15768000"
      SSLCipherSuite 'EDH+CAMELLIA:EDH+aRSA:EECDH+aRSA+AESGCM:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH:+CAMELLIA256:+AES256:+CAMELLIA128:+AES128:+SSLv3:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!DSS:!RC4:!SEED:!ECDSA:CAMELLIA256-SHA:AES256-SHA:CAMELLIA128-SHA:AES128-SHA'
