---
- name: remove unneeded NFS services
  apt: pkg={{ item }} state=absent
  with_items:
    - nfs-common
    - rpcbind

- include: checks.yml
  when: sensu.client.enable_checks|default('True')|bool
  tags: sensu-checks

- include: metrics.yml
  when: sensu.client.enable_metrics|default('True')|bool
  tags: sensu-metrics

- include: serverspec.yml
  when: serverspec.enabled|default("True")|bool
  tags: serverspec
