---
- name: enable packet forwarding
  sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes state=present reload=yes

- name: install ipmi-proxy sync-cache cron
  cron: name="ipmi-proxy sync-cache" user="root"
        cron_file=ipmi-proxy minute="*/10" job="sync-proxy-cache.py"

- name: create ipmi_proxy conf dir
  file: path=/etc/bluebox state=directory mode=0755

- name: create ipmi_proxy data dir
  file: path=/var/lib/ipmi-proxy state=directory mode=0755

- name: install ipmi-proxy conf
  template: src=etc/bluebox/ipmi-proxy.conf dest=/etc/bluebox/ipmi-proxy.conf owner=root group=root mode=0644

- name: create ipmi_proxy lib dir
  file: path=/usr/local/lib/ipmi-proxy state=directory mode=0755

- name: install cgi lib
  shell: cp -a {{ ipmi_proxy.git[0].path }}/src/cgi/* /usr/local/lib/ipmi-proxy

- name: www-data sudoers
  template: src=etc/sudoers.d/www-data
            dest=/etc/sudoers.d/www-data
            owner=root
            group=root
            mode=0440

- name: configure apache
  template: src=etc/apache2/sites-available/ipmi-proxy.conf
            dest=/etc/apache2/sites-available/ipmi-proxy.conf owner=root group=root mode=0644
  notify:
    - restart apache

- name: enable apache mods
  apache2_module: state=present name={{ item }}
  with_items:
    - ssl
    - cgid
    - cache_socache

- name: enable ipmi-proxy vhost
  apache2_site: state=enabled name=ipmi-proxy
  notify:
    - restart apache

- meta: flush_handlers

- include: checks.yml
  when: sensu.client.enable_checks|default('True')|bool
  tags: sensu-checks

- include: metrics.yml
  when: sensu.client.enable_metrics|default('True')|bool
  tags: sensu-metrics

- include: serverspec.yml
  when: serverspec.enabled|default("True")|bool
  tags: serverspec

- name: ensure apache is running
  service: name=apache2 state=started enabled=yes
